//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalSchoolManager
{
    public partial class WebForm17
    {
        protected global::System.Web.UI.WebControls.Label lblCurrentDate;
        protected global::System.Web.UI.WebControls.Panel pnlDashboardStatus;
        protected global::System.Web.UI.WebControls.Label lblDashboardStatus;
        protected global::System.Web.UI.WebControls.Label lblTotalStudents;
        protected global::System.Web.UI.WebControls.Label lblTotalTeachers;
        protected global::System.Web.UI.WebControls.Label lblNonTeachingStaff;
        protected global::System.Web.UI.WebControls.Label lblTotalClasses;
        protected global::System.Web.UI.WebControls.Label lblTodayAdmissions;
        protected global::System.Web.UI.WebControls.Label lblStaffPresent;
        protected global::System.Web.UI.WebControls.Label lblUpcomingExams;
        protected global::System.Web.UI.WebControls.Label lblVacantPosts;
        protected global::System.Web.UI.WebControls.Panel pnlFundSummaryLogin;
        protected global::System.Web.UI.WebControls.Panel pnlFundSummaryAdmin;
        protected global::System.Web.UI.WebControls.Panel pnlFundSummaryUnavailable;
        protected global::System.Web.UI.WebControls.Label lblFundSummaryUnavailable;
        protected global::System.Web.UI.WebControls.Label lblDashboardNsbBalance;
        protected global::System.Web.UI.WebControls.Label lblDashboardFtfWallet;
        protected global::System.Web.UI.WebControls.Label lblDashboardFtfBalance;
        protected global::System.Web.UI.WebControls.Label lblDashboardFtfMonth;
        protected global::System.Web.UI.WebControls.Label lblDashboardFtfTarget;
        protected global::System.Web.UI.WebControls.Label lblDashboardBudgetEstimate;
        protected global::System.Web.UI.WebControls.Label lblDashboardBudgetName;
        protected global::System.Web.UI.WebControls.Label lblDashboardMonthlyExpenditure;
        protected global::System.Web.UI.WebControls.Label lblDashboardMonthlyExpenditureName;
        protected global::System.Web.UI.WebControls.Panel pnlStudentAttendanceLogin;
        protected global::System.Web.UI.WebControls.Panel pnlStudentAttendanceAdmin;
        protected global::System.Web.UI.WebControls.Panel pnlStudentAttendanceUnavailable;
        protected global::System.Web.UI.WebControls.Label lblStudentAttendanceUnavailable;
        protected global::System.Web.UI.WebControls.Label lblStudentPresentToday;
        protected global::System.Web.UI.WebControls.Label lblShortAttendanceCount;
        protected global::System.Web.UI.WebControls.Repeater rptDashboardClassAttendance;
        protected global::System.Web.UI.WebControls.Panel pnlNoDashboardClassAttendance;
        protected global::System.Web.UI.WebControls.Repeater rptDashboardShortAttendance;
        protected global::System.Web.UI.WebControls.Panel pnlNoDashboardShortAttendance;
        protected global::System.Web.UI.WebControls.Panel pnlResultSummaryLogin;
        protected global::System.Web.UI.WebControls.Panel pnlResultSummaryAdmin;
        protected global::System.Web.UI.WebControls.Panel pnlResultSummaryUnavailable;
        protected global::System.Web.UI.WebControls.Label lblResultSummaryUnavailable;
        protected global::System.Web.UI.WebControls.Label lblDashboardResultExam;
        protected global::System.Web.UI.WebControls.Label lblDashboardResultDate;
        protected global::System.Web.UI.WebControls.Label lblExamAppearedStudents;
        protected global::System.Web.UI.WebControls.Label lblExamPassPercentage;
        protected global::System.Web.UI.WebControls.Label lblExamClassesReported;
        protected global::System.Web.UI.WebControls.Repeater rptClassTopStudents;
        protected global::System.Web.UI.WebControls.Panel pnlNoClassTopStudents;
        protected global::System.Web.UI.WebControls.Repeater rptRecentStudents;
        protected global::System.Web.UI.WebControls.Panel pnlNoRecentStudents;
        protected global::System.Web.UI.WebControls.Label lblTeachingAttendance;
        protected global::System.Web.UI.WebControls.Label lblNonTeachingAttendance;
        protected global::System.Web.UI.WebControls.Panel pnlFeeDefaultersLogin;
        protected global::System.Web.UI.WebControls.Panel pnlFeeDefaultersAdmin;
        protected global::System.Web.UI.WebControls.DropDownList ddlDefaulterMonth;
        protected global::System.Web.UI.WebControls.DropDownList ddlDefaulterYear;
        protected global::System.Web.UI.WebControls.Button btnRefreshDefaulters;
        protected global::System.Web.UI.WebControls.Label lblFeeDefaulterCount;
        protected global::System.Web.UI.WebControls.Button btnSendAllReminders;
        protected global::System.Web.UI.WebControls.Panel pnlFeeReminderMessage;
        protected global::System.Web.UI.WebControls.Label lblFeeReminderMessage;
        protected global::System.Web.UI.WebControls.Repeater rptFeeDefaulters;
        protected global::System.Web.UI.WebControls.Panel pnlNoFeeDefaulters;
        protected global::System.Web.UI.WebControls.Repeater rptUpcomingExams;
        protected global::System.Web.UI.WebControls.Panel pnlNoUpcomingExams;
    }
}
