//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalSchoolManager
{
    public partial class BoardResultManagement
    {
        protected global::System.Web.UI.WebControls.Panel pnlMessage;
        protected global::System.Web.UI.WebControls.Label lblMessage;
        protected global::System.Web.UI.WebControls.Label lblSessionCount;
        protected global::System.Web.UI.WebControls.Label lblSubjectRecordCount;
        protected global::System.Web.UI.WebControls.Label lblAboveBoardCount;
        protected global::System.Web.UI.WebControls.Label lblLatestYear;
        protected global::System.Web.UI.WebControls.Label lblSessionEditorTitle;
        protected global::System.Web.UI.WebControls.Button btnNewSession;
        protected global::System.Web.UI.WebControls.HiddenField hfSessionID;
        protected global::System.Web.UI.WebControls.DropDownList ddlClass;
        protected global::System.Web.UI.WebControls.Label lblClassGuidance;
        protected global::System.Web.UI.WebControls.TextBox txtStudyGroup;
        protected global::System.Web.UI.WebControls.TextBox txtExamTitle;
        protected global::System.Web.UI.WebControls.TextBox txtExamYear;
        protected global::System.Web.UI.WebControls.TextBox txtResultDate;
        protected global::System.Web.UI.WebControls.TextBox txtBoardName;
        protected global::System.Web.UI.WebControls.TextBox txtEmisCode;
        protected global::System.Web.UI.WebControls.TextBox txtBiseCode;
        protected global::System.Web.UI.WebControls.DropDownList ddlHeadTeacher;
        protected global::System.Web.UI.WebControls.TextBox txtHeadPeriodFrom;
        protected global::System.Web.UI.WebControls.TextBox txtHeadPeriodTo;
        protected global::System.Web.UI.WebControls.TextBox txtRegisteredCount;
        protected global::System.Web.UI.WebControls.TextBox txtRegisteredYear;
        protected global::System.Web.UI.WebControls.Panel pnlPreviousCohort;
        protected global::System.Web.UI.WebControls.Label lblPreviousAppearedCaption;
        protected global::System.Web.UI.WebControls.TextBox txtPreviousAppearedCount;
        protected global::System.Web.UI.WebControls.Panel pnlPreviousYear;
        protected global::System.Web.UI.WebControls.TextBox txtPreviousAppearedYear;
        protected global::System.Web.UI.WebControls.TextBox txtAppearedCount;
        protected global::System.Web.UI.WebControls.TextBox txtPassedCount;
        protected global::System.Web.UI.WebControls.TextBox txtBoardPassPercentage;
        protected global::System.Web.UI.WebControls.TextBox txtGradeAPlus;
        protected global::System.Web.UI.WebControls.TextBox txtGradeA;
        protected global::System.Web.UI.WebControls.TextBox txtGradeB;
        protected global::System.Web.UI.WebControls.TextBox txtGradeC;
        protected global::System.Web.UI.WebControls.TextBox txtGradeD;
        protected global::System.Web.UI.WebControls.TextBox txtGradeE;
        protected global::System.Web.UI.WebControls.TextBox txtSessionRemarks;
        protected global::System.Web.UI.WebControls.Button btnSaveSession;
        protected global::System.Web.UI.WebControls.Button btnClearSession;
        protected global::System.Web.UI.WebControls.Panel pnlSessionWorkspace;
        protected global::System.Web.UI.WebControls.Label lblWorkspaceTitle;
        protected global::System.Web.UI.WebControls.Label lblWorkspaceMeta;
        protected global::System.Web.UI.WebControls.HyperLink lnkHeadReport;
        protected global::System.Web.UI.WebControls.HyperLink lnkTeacherReport;
        protected global::System.Web.UI.WebControls.HyperLink lnkCompleteReport;
        protected global::System.Web.UI.WebControls.Label lblSubjectEditorTitle;
        protected global::System.Web.UI.WebControls.HiddenField hfSubjectResultID;
        protected global::System.Web.UI.WebControls.DropDownList ddlSubjectTeacher;
        protected global::System.Web.UI.WebControls.DropDownList ddlSubject;
        protected global::System.Web.UI.WebControls.TextBox txtResponsibilityFrom;
        protected global::System.Web.UI.WebControls.TextBox txtResponsibilityTo;
        protected global::System.Web.UI.WebControls.TextBox txtSubjectRegistered;
        protected global::System.Web.UI.WebControls.Panel pnlSubjectPrevious;
        protected global::System.Web.UI.WebControls.TextBox txtSubjectPreviousAppeared;
        protected global::System.Web.UI.WebControls.TextBox txtSubjectAppeared;
        protected global::System.Web.UI.WebControls.TextBox txtSubjectPassed;
        protected global::System.Web.UI.WebControls.TextBox txtSubjectBoardPercentage;
        protected global::System.Web.UI.WebControls.TextBox txtSubjectNotes;
        protected global::System.Web.UI.WebControls.Button btnSaveSubjectResult;
        protected global::System.Web.UI.WebControls.Button btnCancelSubjectEdit;
        protected global::System.Web.UI.WebControls.DropDownList ddlPositionStudent;
        protected global::System.Web.UI.WebControls.DropDownList ddlPositionNumber;
        protected global::System.Web.UI.WebControls.TextBox txtPositionObtained;
        protected global::System.Web.UI.WebControls.TextBox txtPositionTotal;
        protected global::System.Web.UI.WebControls.TextBox txtPositionNotes;
        protected global::System.Web.UI.WebControls.Button btnSavePosition;
        protected global::System.Web.UI.WebControls.GridView gvSubjectResults;
        protected global::System.Web.UI.WebControls.GridView gvPositionHolders;
        protected global::System.Web.UI.WebControls.DropDownList ddlHistoryClass;
        protected global::System.Web.UI.WebControls.TextBox txtHistoryYear;
        protected global::System.Web.UI.WebControls.TextBox txtHistorySearch;
        protected global::System.Web.UI.WebControls.Button btnSearchHistory;
        protected global::System.Web.UI.WebControls.GridView gvSessions;
    }
}
