//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalSchoolManager
{
    public partial class BoardResultReport
    {
        protected global::System.Web.UI.WebControls.Panel pnlReportError;
        protected global::System.Web.UI.WebControls.Label lblReportError;
        protected global::System.Web.UI.WebControls.Panel pnlReport;
        protected global::System.Web.UI.WebControls.Label lblReportTitle;
        protected global::System.Web.UI.WebControls.Label lblReportMeta;
        protected global::System.Web.UI.WebControls.HyperLink lnkBack;
        protected global::System.Web.UI.WebControls.Literal litReport;
    }
}
