//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalSchoolManager
{
    public partial class DaakDiary
    {
        protected global::System.Web.UI.WebControls.Panel pnlMessage;
        protected global::System.Web.UI.WebControls.Label lblMessage;
        protected global::System.Web.UI.WebControls.Panel pnlSavedStamp;
        protected global::System.Web.UI.WebControls.Label lblSavedDiaryNo;
        protected global::System.Web.UI.WebControls.Label lblSavedReceivedDate;
        protected global::System.Web.UI.WebControls.Label lblTotalRecords;
        protected global::System.Web.UI.WebControls.Label lblTodayRecords;
        protected global::System.Web.UI.WebControls.Label lblActiveRecords;
        protected global::System.Web.UI.WebControls.Label lblFiledCopies;
        protected global::System.Web.UI.WebControls.HiddenField hfDiaryID;
        protected global::System.Web.UI.WebControls.ValidationSummary vsDiary;
        protected global::System.Web.UI.WebControls.Label lblReceivedDatePrompt;
        protected global::System.Web.UI.WebControls.TextBox txtReceivedDate;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvReceivedDate;
        protected global::System.Web.UI.WebControls.Label lblLetterDatePrompt;
        protected global::System.Web.UI.WebControls.TextBox txtLetterDate;
        protected global::System.Web.UI.WebControls.Label lblSenderOfficePrompt;
        protected global::System.Web.UI.WebControls.TextBox txtSenderOffice;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvSenderOffice;
        protected global::System.Web.UI.WebControls.Label lblSenderReferencePrompt;
        protected global::System.Web.UI.WebControls.TextBox txtSenderReferenceNo;
        protected global::System.Web.UI.WebControls.Label lblSubjectPrompt;
        protected global::System.Web.UI.WebControls.TextBox txtSubject;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvSubject;
        protected global::System.Web.UI.WebControls.Label lblCategoryPrompt;
        protected global::System.Web.UI.WebControls.DropDownList ddlCategory;
        protected global::System.Web.UI.WebControls.Label lblPriorityPrompt;
        protected global::System.Web.UI.WebControls.DropDownList ddlPriority;
        protected global::System.Web.UI.WebControls.Label lblDeliveryModePrompt;
        protected global::System.Web.UI.WebControls.DropDownList ddlDeliveryMode;
        protected global::System.Web.UI.WebControls.Label lblStatusPrompt;
        protected global::System.Web.UI.WebControls.DropDownList ddlStatus;
        protected global::System.Web.UI.WebControls.Label lblAssignedToPrompt;
        protected global::System.Web.UI.WebControls.TextBox txtAssignedTo;
        protected global::System.Web.UI.WebControls.Label lblActionDueDatePrompt;
        protected global::System.Web.UI.WebControls.TextBox txtActionDueDate;
        protected global::System.Web.UI.WebControls.Label lblDescriptionPrompt;
        protected global::System.Web.UI.WebControls.TextBox txtDescription;
        protected global::System.Web.UI.WebControls.Label lblRemarksPrompt;
        protected global::System.Web.UI.WebControls.TextBox txtRemarks;
        protected global::System.Web.UI.WebControls.Label lblDocumentPrompt;
        protected global::System.Web.UI.WebControls.FileUpload fuDaakDocument;
        protected global::System.Web.UI.WebControls.Button btnSaveDiary;
        protected global::System.Web.UI.WebControls.Button btnClearDiary;
        protected global::System.Web.UI.WebControls.Label lblSearchPrompt;
        protected global::System.Web.UI.WebControls.TextBox txtSearch;
        protected global::System.Web.UI.WebControls.Label lblFilterStatusPrompt;
        protected global::System.Web.UI.WebControls.DropDownList ddlFilterStatus;
        protected global::System.Web.UI.WebControls.Label lblFromDatePrompt;
        protected global::System.Web.UI.WebControls.TextBox txtFromDate;
        protected global::System.Web.UI.WebControls.Label lblToDatePrompt;
        protected global::System.Web.UI.WebControls.TextBox txtToDate;
        protected global::System.Web.UI.WebControls.Button btnSearch;
        protected global::System.Web.UI.WebControls.Button btnResetSearch;
        protected global::System.Web.UI.WebControls.GridView gvDiary;
    }
}
