//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalSchoolManager
{
    public partial class DaakDispatch
    {
        protected global::System.Web.UI.WebControls.Panel pnlMessage;
        protected global::System.Web.UI.WebControls.Label lblMessage;
        protected global::System.Web.UI.WebControls.Panel pnlSavedReceipt;
        protected global::System.Web.UI.WebControls.Label lblSavedDispatchNo;
        protected global::System.Web.UI.WebControls.Label lblSavedDispatchDate;
        protected global::System.Web.UI.WebControls.Label lblTotalRecords;
        protected global::System.Web.UI.WebControls.Label lblTodayRecords;
        protected global::System.Web.UI.WebControls.Label lblActiveRecords;
        protected global::System.Web.UI.WebControls.Label lblFiledCopies;
        protected global::System.Web.UI.WebControls.HiddenField hfDispatchID;
        protected global::System.Web.UI.WebControls.ValidationSummary vsDispatch;
        protected global::System.Web.UI.WebControls.Label lblDispatchDatePrompt;
        protected global::System.Web.UI.WebControls.TextBox txtDispatchDate;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvDispatchDate;
        protected global::System.Web.UI.WebControls.Label lblLetterDatePrompt;
        protected global::System.Web.UI.WebControls.TextBox txtLetterDate;
        protected global::System.Web.UI.WebControls.Label lblRecipientOfficePrompt;
        protected global::System.Web.UI.WebControls.TextBox txtRecipientOffice;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvRecipientOffice;
        protected global::System.Web.UI.WebControls.Label lblRecipientAddressPrompt;
        protected global::System.Web.UI.WebControls.TextBox txtRecipientAddress;
        protected global::System.Web.UI.WebControls.Label lblRecipientContactPrompt;
        protected global::System.Web.UI.WebControls.TextBox txtRecipientContact;
        protected global::System.Web.UI.WebControls.Label lblReferenceNoPrompt;
        protected global::System.Web.UI.WebControls.TextBox txtReferenceNo;
        protected global::System.Web.UI.WebControls.Label lblSubjectPrompt;
        protected global::System.Web.UI.WebControls.TextBox txtSubject;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvSubject;
        protected global::System.Web.UI.WebControls.Label lblCategoryPrompt;
        protected global::System.Web.UI.WebControls.DropDownList ddlCategory;
        protected global::System.Web.UI.WebControls.Label lblPriorityPrompt;
        protected global::System.Web.UI.WebControls.DropDownList ddlPriority;
        protected global::System.Web.UI.WebControls.Label lblDispatchModePrompt;
        protected global::System.Web.UI.WebControls.DropDownList ddlDispatchMode;
        protected global::System.Web.UI.WebControls.Label lblTrackingNoPrompt;
        protected global::System.Web.UI.WebControls.TextBox txtTrackingNo;
        protected global::System.Web.UI.WebControls.Label lblPreparedByPrompt;
        protected global::System.Web.UI.WebControls.TextBox txtPreparedBy;
        protected global::System.Web.UI.WebControls.Label lblSignedByPrompt;
        protected global::System.Web.UI.WebControls.TextBox txtSignedBy;
        protected global::System.Web.UI.WebControls.Label lblStatusPrompt;
        protected global::System.Web.UI.WebControls.DropDownList ddlStatus;
        protected global::System.Web.UI.WebControls.Label lblDescriptionPrompt;
        protected global::System.Web.UI.WebControls.TextBox txtDescription;
        protected global::System.Web.UI.WebControls.Label lblRemarksPrompt;
        protected global::System.Web.UI.WebControls.TextBox txtRemarks;
        protected global::System.Web.UI.WebControls.Label lblDocumentPrompt;
        protected global::System.Web.UI.WebControls.FileUpload fuDispatchDocument;
        protected global::System.Web.UI.WebControls.Button btnSaveDispatch;
        protected global::System.Web.UI.WebControls.Button btnClearDispatch;
        protected global::System.Web.UI.WebControls.Label lblSearchPrompt;
        protected global::System.Web.UI.WebControls.TextBox txtSearch;
        protected global::System.Web.UI.WebControls.Label lblFilterStatusPrompt;
        protected global::System.Web.UI.WebControls.DropDownList ddlFilterStatus;
        protected global::System.Web.UI.WebControls.Label lblFromDatePrompt;
        protected global::System.Web.UI.WebControls.TextBox txtFromDate;
        protected global::System.Web.UI.WebControls.Label lblToDatePrompt;
        protected global::System.Web.UI.WebControls.TextBox txtToDate;
        protected global::System.Web.UI.WebControls.Button btnSearch;
        protected global::System.Web.UI.WebControls.Button btnResetSearch;
        protected global::System.Web.UI.WebControls.GridView gvDispatch;
    }
}
