//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalSchoolManager
{
    public partial class DataBackup
    {
        protected global::System.Web.UI.WebControls.Panel pnlMessage;
        protected global::System.Web.UI.WebControls.Label lblMessage;
        protected global::System.Web.UI.WebControls.Label lblDatabaseName;
        protected global::System.Web.UI.WebControls.Label lblBackupFolder;
        protected global::System.Web.UI.WebControls.Label lblBackupCount;
        protected global::System.Web.UI.WebControls.Label lblLatestBackup;
        protected global::System.Web.UI.WebControls.Button btnCreateBackup;
        protected global::System.Web.UI.WebControls.RadioButtonList rblRestoreSource;
        protected global::System.Web.UI.WebControls.Label lblStoredBackupPrompt;
        protected global::System.Web.UI.WebControls.DropDownList ddlStoredBackups;
        protected global::System.Web.UI.WebControls.Label lblUploadPrompt;
        protected global::System.Web.UI.WebControls.FileUpload fuRestoreBackup;
        protected global::System.Web.UI.WebControls.CheckBox chkConfirmRestore;
        protected global::System.Web.UI.WebControls.Button btnRestoreBackup;
        protected global::System.Web.UI.WebControls.Button btnRefreshBackups;
        protected global::System.Web.UI.WebControls.GridView gvBackups;
    }
}
