//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalSchoolManager
{


    public partial class DSM
    {

        /// <summary>
        /// head control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ContentPlaceHolder head;

        /// <summary>
        /// form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
        /// pnlGuestSession control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlGuestSession;

        /// <summary>
        /// lnkLogin control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HyperLink lnkLogin;

        /// <summary>
        /// pnlUserSession control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlUserSession;

        /// <summary>
        /// lblSignedInRole control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblSignedInRole;

        /// <summary>
        /// lblSignedInUser control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblSignedInUser;

        /// <summary>
        /// btnLogout control.
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton btnLogout;

        /// <summary>
        /// MenuHome control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Menu MenuHome;

        protected global::System.Web.UI.WebControls.Menu MenuTeacher;

        /// <summary>
        /// MainContent control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ContentPlaceHolder MainContent;
    }
}
