//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalSchoolManager
{
    public partial class FeeCollection
    {
        protected global::System.Web.UI.HtmlControls.HtmlAnchor lnkFeeRates;
        protected global::System.Web.UI.WebControls.Panel pnlMessage;
        protected global::System.Web.UI.WebControls.Label lblMessage;
        protected global::System.Web.UI.WebControls.Label lblFeeMonthPrompt;
        protected global::System.Web.UI.WebControls.DropDownList ddlFeeMonth;
        protected global::System.Web.UI.WebControls.Label lblFeeYearPrompt;
        protected global::System.Web.UI.WebControls.DropDownList ddlFeeYear;
        protected global::System.Web.UI.WebControls.Label lblClassPrompt;
        protected global::System.Web.UI.WebControls.DropDownList ddlClass;
        protected global::System.Web.UI.WebControls.Label lblSearchPrompt;
        protected global::System.Web.UI.WebControls.TextBox txtStudentSearch;
        protected global::System.Web.UI.WebControls.Button btnSearchStudent;
        protected global::System.Web.UI.WebControls.Label lblStudentPrompt;
        protected global::System.Web.UI.WebControls.DropDownList ddlStudent;
        protected global::System.Web.UI.WebControls.Button btnClearSelection;
        protected global::System.Web.UI.WebControls.Panel pnlVoucher;
        protected global::System.Web.UI.WebControls.HiddenField hfStudentID;
        protected global::System.Web.UI.WebControls.HiddenField hfClassID;
        protected global::System.Web.UI.WebControls.HiddenField hfVoucherNo;
        protected global::System.Web.UI.WebControls.HiddenField hfCalculatedTotal;
        protected global::System.Web.UI.WebControls.Label lblVoucherNo;
        protected global::System.Web.UI.WebControls.Label lblFeePeriod;
        protected global::System.Web.UI.WebControls.TextBox txtDepositDate;
        protected global::System.Web.UI.WebControls.Label lblStudentInitials;
        protected global::System.Web.UI.WebControls.Label lblStudentName;
        protected global::System.Web.UI.WebControls.Label lblFatherName;
        protected global::System.Web.UI.WebControls.Label lblRegistrationNo;
        protected global::System.Web.UI.WebControls.Label lblFormBNo;
        protected global::System.Web.UI.WebControls.Label lblClassName;
        protected global::System.Web.UI.WebControls.Label lblRollNo;
        protected global::System.Web.UI.WebControls.Panel pnlAlreadyPaid;
        protected global::System.Web.UI.WebControls.Label lblPaidPeriod;
        protected global::System.Web.UI.WebControls.GridView gvFeeItems;
        protected global::System.Web.UI.WebControls.Label lblRemarksPrompt;
        protected global::System.Web.UI.WebControls.TextBox txtRemarks;
        protected global::System.Web.UI.WebControls.Panel pnlSavedVoucher;
        protected global::System.Web.UI.WebControls.Label lblSavedVoucherNo;
        protected global::System.Web.UI.WebControls.Label lblSavedTotal;
        protected global::System.Web.UI.WebControls.Button btnSaveVoucher;
    }
}
