<%@ Page Title="Laboratory Records" Language="C#" MasterPageFile="~/DSM.Master" AutoEventWireup="true" CodeBehind="LaboratoryRecords.aspx.cs" Inherits="DigitalSchoolManager.LaboratoryRecords" %>
<asp:Content ID="HeadContent" ContentPlaceHolderID="head" runat="server" />
<asp:Content ID="MainContentBlock" ContentPlaceHolderID="MainContent" runat="server">
<section class="resource-page laboratory-page">
    <header class="resource-hero lab-hero"><div><span class="module-kicker">LABORATORY CONTROL REGISTER</span><h1>School Laboratory Records</h1><p>Manage laboratories, equipment inventories, functional status, inspections, disposal and supporting evidence.</p></div><div class="resource-hero-badge"><strong>Evidence-led inventory</strong><span>Computer, Science, Chemistry and specialist labs</span></div></header>
    <asp:Panel ID="pnlMessage" runat="server" Visible="false" CssClass="module-message"><asp:Label ID="lblMessage" runat="server" /></asp:Panel>

    <div class="laboratory-layout">
        <article class="module-card no-print">
            <div class="module-card-head"><div><span class="module-kicker">LAB PROFILE</span><h2><asp:Label ID="lblLabEditorTitle" runat="server" Text="Create laboratory record" /></h2></div><asp:Button ID="btnNewLab" runat="server" Text="New Lab" CssClass="module-button secondary" OnClick="btnNewLab_Click" CausesValidation="false" /></div>
            <asp:HiddenField ID="hidLabID" runat="server" />
            <div class="module-form-grid two-column">
                <label>Laboratory name<asp:TextBox ID="txtLabName" runat="server" CssClass="module-input" placeholder="e.g. Computer Laboratory" /></label>
                <label>Laboratory type<asp:DropDownList ID="ddlLabType" runat="server" CssClass="module-input"><asp:ListItem>Computer Lab</asp:ListItem><asp:ListItem>General Science Lab</asp:ListItem><asp:ListItem>Chemistry Lab</asp:ListItem><asp:ListItem>Physics Lab</asp:ListItem><asp:ListItem>Biology Lab</asp:ListItem><asp:ListItem>Home Economics Lab</asp:ListItem><asp:ListItem>Technical Lab</asp:ListItem><asp:ListItem>Other</asp:ListItem></asp:DropDownList></label>
                <label>Lab incharge<asp:TextBox ID="txtLabIncharge" runat="server" CssClass="module-input" /></label><label>Location<asp:TextBox ID="txtLabLocation" runat="server" CssClass="module-input" placeholder="Block and room" /></label>
                <label>Safety status<asp:DropDownList ID="ddlSafetyStatus" runat="server" CssClass="module-input"><asp:ListItem>Satisfactory</asp:ListItem><asp:ListItem>Attention Required</asp:ListItem><asp:ListItem>Restricted Use</asp:ListItem><asp:ListItem>Unsafe / Closed</asp:ListItem></asp:DropDownList></label><label>Last inspection<asp:TextBox ID="txtLabInspectionDate" runat="server" CssClass="module-input" TextMode="Date" /></label>
                <label class="check-field"><asp:CheckBox ID="chkLabActive" runat="server" Checked="true" Text="Laboratory is active" /></label>
                <label class="span-two">Description, facilities and safety notes<asp:TextBox ID="txtLabDescription" runat="server" CssClass="module-input" TextMode="MultiLine" Rows="3" /></label>
                <label class="span-two resource-upload">Lab inspection sheets or scanned evidence<asp:FileUpload ID="fuLabDocuments" runat="server" CssClass="module-input" AllowMultiple="true" accept=".jpg,.jpeg,.png,.gif,.bmp,.pdf" /><small>Images are optimized to 1 MB; each PDF may be up to 5 MB.</small></label>
            </div>
            <div class="module-actions"><asp:Button ID="btnSaveLab" runat="server" Text="Save Laboratory" CssClass="module-button" OnClick="btnSaveLab_Click" /></div>
        </article>

        <article class="module-card laboratory-list-card">
            <div class="module-card-head"><div><span class="module-kicker">LABORATORIES</span><h2>Select a lab to manage equipment</h2></div><button type="button" class="module-button secondary no-print" onclick="window.print()">Print Inventory</button></div>
            <div class="resource-filters no-print"><asp:TextBox ID="txtLabSearch" runat="server" CssClass="module-input" placeholder="Lab name, code, type or incharge" /><label class="check-field compact"><asp:CheckBox ID="chkIncludeInactiveLabs" runat="server" Text="Include inactive" /></label><asp:Button ID="btnSearchLabs" runat="server" Text="Search Labs" CssClass="module-button" OnClick="btnSearchLabs_Click" CausesValidation="false" /></div>
            <div class="module-table-wrap"><asp:GridView ID="gvLabs" runat="server" AutoGenerateColumns="false" CssClass="module-table" EmptyDataText="No laboratory records are available." OnRowCommand="gvLabs_RowCommand"><Columns>
                <asp:BoundField DataField="LabCode" HeaderText="Lab Code" /><asp:BoundField DataField="LabName" HeaderText="Laboratory" /><asp:BoundField DataField="LabType" HeaderText="Type" /><asp:BoundField DataField="InchargeName" HeaderText="Incharge" /><asp:BoundField DataField="TotalItems" HeaderText="Items" /><asp:BoundField DataField="FunctionalItems" HeaderText="Functional" /><asp:BoundField DataField="SafetyStatus" HeaderText="Safety" />
                <asp:TemplateField HeaderText="Actions" ItemStyle-CssClass="no-print" HeaderStyle-CssClass="no-print"><ItemTemplate><asp:LinkButton ID="btnManage" runat="server" Text="Equipment" CommandName="ManageLab" CommandArgument='<%# Eval("LabID") %>' CssClass="table-action table-action-view" CausesValidation="false" /><asp:LinkButton ID="btnEdit" runat="server" Text="Edit" CommandName="EditLab" CommandArgument='<%# Eval("LabID") %>' CssClass="table-action table-action-edit" CausesValidation="false" /><asp:LinkButton ID="btnFiles" runat="server" Text="Files" CommandName="LabFiles" CommandArgument='<%# Eval("LabID") %>' CssClass="table-action table-action-view" CausesValidation="false" /></ItemTemplate></asp:TemplateField>
            </Columns></asp:GridView></div>
        </article>
    </div>

    <asp:Panel ID="pnlEquipment" runat="server" Visible="false" CssClass="laboratory-equipment-section">
        <div class="laboratory-selected-banner"><div><span>SELECTED LABORATORY</span><h2><asp:Label ID="lblSelectedLab" runat="server" /></h2><p><asp:Label ID="lblSelectedLabMeta" runat="server" /></p></div><asp:Button ID="btnCloseEquipment" runat="server" Text="Close Equipment Workspace" CssClass="module-button secondary no-print" OnClick="btnCloseEquipment_Click" CausesValidation="false" /></div>
        <div class="laboratory-layout">
            <article class="module-card no-print">
                <div class="module-card-head"><div><span class="module-kicker">EQUIPMENT ENTRY</span><h2><asp:Label ID="lblEquipmentEditorTitle" runat="server" Text="Add laboratory equipment" /></h2></div><asp:Button ID="btnNewEquipment" runat="server" Text="New Equipment" CssClass="module-button secondary" OnClick="btnNewEquipment_Click" CausesValidation="false" /></div>
                <asp:HiddenField ID="hidSelectedLabID" runat="server" /><asp:HiddenField ID="hidEquipmentID" runat="server" />
                <div class="module-form-grid three-column">
                    <label>Equipment / material name<asp:TextBox ID="txtEquipmentName" runat="server" CssClass="module-input" /></label><label>Category<asp:TextBox ID="txtEquipmentCategory" runat="server" CssClass="module-input" placeholder="Computer, glassware, chemical, apparatus" /></label><label>Unit<asp:DropDownList ID="ddlEquipmentUnit" runat="server" CssClass="module-input"><asp:ListItem>Item</asp:ListItem><asp:ListItem>Number</asp:ListItem><asp:ListItem>Set</asp:ListItem><asp:ListItem>Kit</asp:ListItem><asp:ListItem>Pack</asp:ListItem><asp:ListItem>Kg</asp:ListItem><asp:ListItem>Litre</asp:ListItem></asp:DropDownList></label>
                    <label>Total quantity<asp:TextBox ID="txtEquipmentQuantity" runat="server" CssClass="module-input" TextMode="Number" min="0" Text="1" /></label><label>Working quantity<asp:TextBox ID="txtWorkingQuantity" runat="server" CssClass="module-input" TextMode="Number" min="0" Text="1" /></label><label>Non-functional quantity<asp:TextBox ID="txtNonFunctionalQuantity" runat="server" CssClass="module-input" TextMode="Number" min="0" Text="0" /></label>
                    <label>Condition<asp:DropDownList ID="ddlEquipmentCondition" runat="server" CssClass="module-input"><asp:ListItem>Functional</asp:ListItem><asp:ListItem>Partly Functional</asp:ListItem><asp:ListItem>Repair Required</asp:ListItem><asp:ListItem>Non-functional</asp:ListItem><asp:ListItem>Disposed</asp:ListItem></asp:DropDownList></label><label>Equipment location<asp:TextBox ID="txtEquipmentLocation" runat="server" CssClass="module-input" placeholder="Cabinet, bench or rack" /></label><label>Purchase date<asp:TextBox ID="txtEquipmentPurchaseDate" runat="server" CssClass="module-input" TextMode="Date" /></label>
                    <label>Purchase value (Rs.)<asp:TextBox ID="txtEquipmentPurchaseAmount" runat="server" CssClass="module-input" TextMode="Number" step="0.01" min="0" /></label><label class="check-field"><asp:CheckBox ID="chkEquipmentDisposed" runat="server" Text="Equipment is disposed" /></label><label>Disposal date<asp:TextBox ID="txtEquipmentDisposalDate" runat="server" CssClass="module-input" TextMode="Date" /></label>
                    <label class="span-two">Notes / specifications<asp:TextBox ID="txtEquipmentNotes" runat="server" CssClass="module-input" TextMode="MultiLine" Rows="3" /></label><label>Disposal remarks<asp:TextBox ID="txtEquipmentDisposalRemarks" runat="server" CssClass="module-input" TextMode="MultiLine" Rows="3" /></label>
                    <label class="span-three resource-upload">Receipt, stock page or condition evidence<asp:FileUpload ID="fuEquipmentDocuments" runat="server" CssClass="module-input" AllowMultiple="true" accept=".jpg,.jpeg,.png,.gif,.bmp,.pdf" /></label>
                </div>
                <div class="module-actions"><asp:Button ID="btnSaveEquipment" runat="server" Text="Save Equipment" CssClass="module-button" OnClick="btnSaveEquipment_Click" /></div>
            </article>
            <article class="module-card resource-register">
                <div class="module-card-head"><div><span class="module-kicker">LIVE INVENTORY</span><h2>Equipment status register</h2></div></div>
                <div class="module-table-wrap"><asp:GridView ID="gvEquipment" runat="server" AutoGenerateColumns="false" CssClass="module-table resource-table" EmptyDataText="No equipment is recorded for this laboratory." OnRowCommand="gvEquipment_RowCommand"><Columns>
                    <asp:BoundField DataField="EquipmentCode" HeaderText="Code" /><asp:BoundField DataField="EquipmentName" HeaderText="Equipment" /><asp:BoundField DataField="EquipmentCategory" HeaderText="Category" /><asp:BoundField DataField="Quantity" HeaderText="Total" /><asp:BoundField DataField="WorkingQuantity" HeaderText="Working" /><asp:BoundField DataField="NonFunctionalQuantity" HeaderText="Non-functional" /><asp:BoundField DataField="ConditionStatus" HeaderText="Condition" /><asp:BoundField DataField="DocumentCount" HeaderText="Files" />
                    <asp:TemplateField HeaderText="Actions" ItemStyle-CssClass="no-print" HeaderStyle-CssClass="no-print"><ItemTemplate><asp:LinkButton ID="btnEdit" runat="server" Text="Edit" CommandName="EditEquipment" CommandArgument='<%# Eval("EquipmentID") %>' CssClass="table-action table-action-edit" CausesValidation="false" /><asp:LinkButton ID="btnFiles" runat="server" Text="Evidence" CommandName="EquipmentFiles" CommandArgument='<%# Eval("EquipmentID") %>' CssClass="table-action table-action-view" CausesValidation="false" /></ItemTemplate></asp:TemplateField>
                </Columns></asp:GridView></div>
            </article>
        </div>
    </asp:Panel>

    <asp:Panel ID="pnlDocuments" runat="server" Visible="false" CssClass="module-card resource-documents no-print">
        <div class="module-card-head"><div><span class="module-kicker">SCANNED EVIDENCE</span><h2><asp:Label ID="lblDocumentTitle" runat="server" /></h2></div><asp:Button ID="btnCloseDocuments" runat="server" Text="Close" CssClass="module-button secondary" OnClick="btnCloseDocuments_Click" CausesValidation="false" /></div>
        <asp:HiddenField ID="hidDocumentResourceType" runat="server" /><asp:HiddenField ID="hidDocumentResourceID" runat="server" />
        <div class="module-table-wrap"><asp:GridView ID="gvDocuments" runat="server" AutoGenerateColumns="false" CssClass="module-table" EmptyDataText="No evidence files are attached."><Columns><asp:BoundField DataField="DocumentType" HeaderText="Type" /><asp:BoundField DataField="OriginalFileName" HeaderText="File" /><asp:TemplateField HeaderText="Size"><ItemTemplate><%# FormatFileSize(Eval("FileSizeBytes")) %></ItemTemplate></asp:TemplateField><asp:BoundField DataField="UploadedAtUtc" HeaderText="Uploaded" DataFormatString="{0:dd MMM yyyy}" /><asp:TemplateField HeaderText="Actions"><ItemTemplate><a class="table-action table-action-view" target="_blank" href='<%# "SchoolResourceDocument.ashx?id="+Eval("DocumentID") %>'>View</a><a class="table-action table-action-edit" href='<%# "SchoolResourceDocument.ashx?id="+Eval("DocumentID")+"&download=1" %>'>Download</a></ItemTemplate></asp:TemplateField></Columns></asp:GridView></div>
        <div class="resource-add-files"><label>Evidence type<asp:DropDownList ID="ddlDocumentType" runat="server" CssClass="module-input"><asp:ListItem>Receipt</asp:ListItem><asp:ListItem>Stock Register Page</asp:ListItem><asp:ListItem>Inspection Evidence</asp:ListItem><asp:ListItem>Repair Record</asp:ListItem><asp:ListItem>Disposal Evidence</asp:ListItem><asp:ListItem>Other Evidence</asp:ListItem></asp:DropDownList></label><label>Add files<asp:FileUpload ID="fuMoreDocuments" runat="server" CssClass="module-input" AllowMultiple="true" accept=".jpg,.jpeg,.png,.gif,.bmp,.pdf" /></label><asp:Button ID="btnAddDocuments" runat="server" Text="Upload Files" CssClass="module-button" OnClick="btnAddDocuments_Click" /></div>
    </asp:Panel>
</section>
</asp:Content>
