namespace DigitalSchoolManager
{
    public partial class LaboratoryRecords
    {
        protected global::System.Web.UI.WebControls.Panel pnlMessage; protected global::System.Web.UI.WebControls.Label lblMessage;
        protected global::System.Web.UI.WebControls.Label lblLabEditorTitle; protected global::System.Web.UI.WebControls.Button btnNewLab; protected global::System.Web.UI.WebControls.HiddenField hidLabID;
        protected global::System.Web.UI.WebControls.TextBox txtLabName; protected global::System.Web.UI.WebControls.DropDownList ddlLabType; protected global::System.Web.UI.WebControls.TextBox txtLabIncharge; protected global::System.Web.UI.WebControls.TextBox txtLabLocation; protected global::System.Web.UI.WebControls.DropDownList ddlSafetyStatus; protected global::System.Web.UI.WebControls.TextBox txtLabInspectionDate; protected global::System.Web.UI.WebControls.CheckBox chkLabActive; protected global::System.Web.UI.WebControls.TextBox txtLabDescription; protected global::System.Web.UI.WebControls.FileUpload fuLabDocuments; protected global::System.Web.UI.WebControls.Button btnSaveLab;
        protected global::System.Web.UI.WebControls.TextBox txtLabSearch; protected global::System.Web.UI.WebControls.CheckBox chkIncludeInactiveLabs; protected global::System.Web.UI.WebControls.Button btnSearchLabs; protected global::System.Web.UI.WebControls.GridView gvLabs;
        protected global::System.Web.UI.WebControls.Panel pnlEquipment; protected global::System.Web.UI.WebControls.Label lblSelectedLab; protected global::System.Web.UI.WebControls.Label lblSelectedLabMeta; protected global::System.Web.UI.WebControls.Button btnCloseEquipment; protected global::System.Web.UI.WebControls.Label lblEquipmentEditorTitle; protected global::System.Web.UI.WebControls.Button btnNewEquipment; protected global::System.Web.UI.WebControls.HiddenField hidSelectedLabID; protected global::System.Web.UI.WebControls.HiddenField hidEquipmentID;
        protected global::System.Web.UI.WebControls.TextBox txtEquipmentName; protected global::System.Web.UI.WebControls.TextBox txtEquipmentCategory; protected global::System.Web.UI.WebControls.DropDownList ddlEquipmentUnit; protected global::System.Web.UI.WebControls.TextBox txtEquipmentQuantity; protected global::System.Web.UI.WebControls.TextBox txtWorkingQuantity; protected global::System.Web.UI.WebControls.TextBox txtNonFunctionalQuantity; protected global::System.Web.UI.WebControls.DropDownList ddlEquipmentCondition; protected global::System.Web.UI.WebControls.TextBox txtEquipmentLocation; protected global::System.Web.UI.WebControls.TextBox txtEquipmentPurchaseDate; protected global::System.Web.UI.WebControls.TextBox txtEquipmentPurchaseAmount; protected global::System.Web.UI.WebControls.CheckBox chkEquipmentDisposed; protected global::System.Web.UI.WebControls.TextBox txtEquipmentDisposalDate; protected global::System.Web.UI.WebControls.TextBox txtEquipmentNotes; protected global::System.Web.UI.WebControls.TextBox txtEquipmentDisposalRemarks; protected global::System.Web.UI.WebControls.FileUpload fuEquipmentDocuments; protected global::System.Web.UI.WebControls.Button btnSaveEquipment; protected global::System.Web.UI.WebControls.GridView gvEquipment;
        protected global::System.Web.UI.WebControls.Panel pnlDocuments; protected global::System.Web.UI.WebControls.Label lblDocumentTitle; protected global::System.Web.UI.WebControls.Button btnCloseDocuments; protected global::System.Web.UI.WebControls.HiddenField hidDocumentResourceType; protected global::System.Web.UI.WebControls.HiddenField hidDocumentResourceID; protected global::System.Web.UI.WebControls.GridView gvDocuments; protected global::System.Web.UI.WebControls.DropDownList ddlDocumentType; protected global::System.Web.UI.WebControls.FileUpload fuMoreDocuments; protected global::System.Web.UI.WebControls.Button btnAddDocuments;
    }
}
