//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalSchoolManager
{
    public partial class Login
    {
        protected global::System.Web.UI.WebControls.Panel pnlMessage;
        protected global::System.Web.UI.WebControls.Label lblMessage;
        protected global::System.Web.UI.WebControls.Panel pnlLoginForm;
        protected global::System.Web.UI.WebControls.Label lblUsernamePrompt;
        protected global::System.Web.UI.WebControls.TextBox txtUsername;
        protected global::System.Web.UI.WebControls.Label lblPasswordPrompt;
        protected global::System.Web.UI.WebControls.TextBox txtPassword;
        protected global::System.Web.UI.WebControls.CheckBox chkRememberMe;
        protected global::System.Web.UI.WebControls.Button btnLogin;
        protected global::System.Web.UI.WebControls.LinkButton btnShowForgotPassword;
        protected global::System.Web.UI.WebControls.Panel pnlPasswordRecovery;
        protected global::System.Web.UI.WebControls.Label lblRecoveryUsernamePrompt;
        protected global::System.Web.UI.WebControls.TextBox txtRecoveryUsername;
        protected global::System.Web.UI.WebControls.Label lblRecoveryCnicPrompt;
        protected global::System.Web.UI.WebControls.TextBox txtRecoveryCnic;
        protected global::System.Web.UI.WebControls.Label lblRecoveryPersonalNoPrompt;
        protected global::System.Web.UI.WebControls.TextBox txtRecoveryPersonalNo;
        protected global::System.Web.UI.WebControls.Label lblRecoveryPasswordPrompt;
        protected global::System.Web.UI.WebControls.TextBox txtRecoveryPassword;
        protected global::System.Web.UI.WebControls.Label lblRecoveryConfirmPrompt;
        protected global::System.Web.UI.WebControls.TextBox txtRecoveryConfirm;
        protected global::System.Web.UI.WebControls.Button btnResetPassword;
        protected global::System.Web.UI.WebControls.Button btnCancelRecovery;
        protected global::System.Web.UI.WebControls.Panel pnlAdminTransfer;
        protected global::System.Web.UI.WebControls.Label lblCurrentAdministrator;
        protected global::System.Web.UI.WebControls.Label lblTransferTeacherPrompt;
        protected global::System.Web.UI.WebControls.DropDownList ddlNewAdministrator;
        protected global::System.Web.UI.WebControls.Label lblTransferUsernamePrompt;
        protected global::System.Web.UI.WebControls.TextBox txtTransferUsername;
        protected global::System.Web.UI.WebControls.Label lblTransferPasswordPrompt;
        protected global::System.Web.UI.WebControls.TextBox txtTransferPassword;
        protected global::System.Web.UI.WebControls.Label lblTransferConfirmPrompt;
        protected global::System.Web.UI.WebControls.TextBox txtTransferConfirm;
        protected global::System.Web.UI.WebControls.Label lblCurrentPasswordPrompt;
        protected global::System.Web.UI.WebControls.TextBox txtCurrentAdminPassword;
        protected global::System.Web.UI.WebControls.CheckBox chkDeactivateCurrentAdmin;
        protected global::System.Web.UI.WebControls.Button btnTransferAdministrator;
        protected global::System.Web.UI.WebControls.Panel pnlFirstAdminSetup;
        protected global::System.Web.UI.WebControls.Label lblTeacherPrompt;
        protected global::System.Web.UI.WebControls.DropDownList ddlTeacher;
        protected global::System.Web.UI.WebControls.Label lblNewUsernamePrompt;
        protected global::System.Web.UI.WebControls.TextBox txtNewUsername;
        protected global::System.Web.UI.WebControls.Label lblNewPasswordPrompt;
        protected global::System.Web.UI.WebControls.TextBox txtNewPassword;
        protected global::System.Web.UI.WebControls.Label lblConfirmPasswordPrompt;
        protected global::System.Web.UI.WebControls.TextBox txtConfirmPassword;
        protected global::System.Web.UI.WebControls.Button btnCreateAdministrator;
    }
}
